baseURL = "/"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "./themes"
title = "Hugo Serif Theme"
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
name = "Testimonials"
url = "/testimonials/"
weight = 3
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[params]
google_analytics_id = ""
